-- ALTER COMMANDS

use codedb;

create table st(
st_id int primary key,
st_name varchar(50));

DESC nt;

-- ADD THE COLUMN IN A TABLE
ALTER TABLE st
ADD COLUMN st_city varchar(20) not null;

-- MODIFY THE DATA_TYPE OF A COLUMN
ALTER TABLE st
MODIFY st_name CHAR(30);

-- WANT TO RENAME THE COLUMN
ALTER TABLE st
RENAME COLUMN st_city TO city;

-- DELETE THE COLUMN
ALTER TABLE st
DROP COLUMN city;

-- If you want rename table
ALTER TABLE st 
RENAME TO nt;

-- IF YOU WANT TO ADD ANY CONSTRAINT
ALTER TABLE nt
ADD CONSTRAINT st_name unique(st_name);

ALTER TABLE nt
ADD CONSTRAINT st_id primary key(st_id);

-- IF YOU WANT DELETE THE CONSTRAINT
ALTER TABLE nt
DROP CONSTRAINT st_name;

-- DDL (DATA DEFINATION LANGUAGE)
-- CREATE
-- ALTER
-- DROP
-- RENAME
-- TRUNCATE
-- COMMENT

-- DML (DATA MANIPULATION LANGUAGE)
-- UPDATE
-- DELETE

-- DQL (DATA QUERY LANGUAGE)
-- SELECT

-- TCL (TRANSACTION CONTROL LANGUAGE)
-- COMMIT (SAVE CHANGES)
-- ROLLBACK (UNDO CHANGES)
-- SAVEPOINT (SET ACHECKPOINT)

-- DCL (DATA CONTROL LANGUAGE)
-- GRANT (GIVE PERMISSIONS)
-- REVOKE (REMOVE PERMISSIONS)

-- FOREIGN KEY , JOINS , TRIGGERS , PROCEDURES , VIEWS , WINDOW FUNCTION , 
-- LOOPS , CONDITIONS ETC...