-- Joins
-- What is Joins? 
-- Joining two or more  table .

-- 5 Joins
-- Left
-- Right
-- Inner
-- Full
-- Self

-- Left Executive Join
-- Right Executive Join

USE CODEDB;

-- WE ARE FINDING OUT THAT WHICH STUDENT HAS TAKEN ANY OF COMMON SUBJECT
CREATE TABLE STUDENT_T(
ST_ID INT PRIMARY KEY,
ST_NAME VARCHAR(30),
ST_SUBJECT_ID INT);

INSERT INTO STUDENT_T VALUES
(1101,"NISHA",101),
(1102,"MANISH",102),
(1103,"NITIN",103),
(1104,"MANI",101),
(1105,"NISHU",101),
(1106,"MAMTA",102),
(1107,"NIKITA",104),
(1108,"MANNU",105);

CREATE TABLE PROFESSOR(
PR_ID INT PRIMARY KEY,
PR_NAME VARCHAR(30),
PR_SUBJECT_ID VARCHAR(30));

DROP TABLE STUDENT_T;

INSERT INTO PROFESSOR VALUES
(1,"VINOD",101),
(2,"SATISH",102);

INSERT INTO PROFESSOR VALUES
(3,"SURESH",103);

INSERT INTO PROFESSOR VALUES
(4,"VINEET",108);

-- INNER JOIN : COMMON DATA B/W TWO TABLES
SELECT S1.PR_ID,S1.PR_NAME,S2.ST_ID,S2.ST_NAME
FROM PROFESSOR AS S1 
INNER JOIN STUDENT_T AS S2
ON S1.PR_SUBJECT_ID = S2.ST_SUBJECT_ID;

-- LEFT JOIN : LEFT TABLE DATA & COMMON DATA B/W TWO TABLES
SELECT S1.PR_ID,S1.PR_NAME,S2.ST_ID,S2.ST_NAME
FROM PROFESSOR AS S1 
LEFT JOIN STUDENT_T AS S2
ON S1.PR_SUBJECT_ID = S2.ST_SUBJECT_ID;

-- RIGHT JOIN : RIGHT TABLE DATA & COMMON DAT B/W TWO TABLES
SELECT S1.PR_ID,S1.PR_NAME,S2.ST_ID,S2.ST_NAME
FROM PROFESSOR AS S1 
RIGHT JOIN STUDENT_T AS S2
ON S1.PR_SUBJECT_ID = S2.ST_SUBJECT_ID;

-- FULL JOIN : MS SQL, ORACLE
SELECT S1.PR_ID,S1.PR_NAME,S2.ST_ID,S2.ST_NAME
FROM PROFESSOR AS S1 
LEFT JOIN STUDENT_T AS S2
ON S1.PR_SUBJECT_ID = S2.ST_SUBJECT_ID
UNION
SELECT S1.PR_ID,S1.PR_NAME,S2.ST_ID,S2.ST_NAME
FROM PROFESSOR AS S1 
RIGHT JOIN STUDENT_T AS S2
ON S1.PR_SUBJECT_ID = S2.ST_SUBJECT_ID;

-- LEFT EXECUTIVE JOIN
SELECT S1.PR_ID,S1.PR_NAME,S2.ST_ID,S2.ST_NAME
FROM PROFESSOR AS S1 
LEFT JOIN STUDENT_T AS S2
ON S1.PR_SUBJECT_ID = S2.ST_SUBJECT_ID
WHERE S2.ST_SUBJECT_ID IS NULL;

-- RIGHT EXECUTIVE JOIN
SELECT S1.PR_ID,S1.PR_NAME,S2.ST_ID,S2.ST_NAME
FROM PROFESSOR AS S1 
RIGHT JOIN STUDENT_T AS S2
ON S1.PR_SUBJECT_ID = S2.ST_SUBJECT_ID
WHERE S1.PR_SUBJECT_ID IS NULL;

SELECT * FROM STUDENT_T;