UPDATE employees
SET salary=salary+(salary*15)/100
WHERE department="Marketing" or department="Finance";

SELECT * FROM EMPLOYEES;

-- Aggreagate Operators : sum , avg , min , max , count
SELECT SUM(SALARY) FROM EMPLOYEES;
SELECT COUNT(*) FROM EMPOYEES;
SELECT AVG(SALARY) FROM EMPLOYEES;
SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT MIN(SALARY) FROM EMPLOYEES;

-- IN HR DEPARTMENT WHAT IS THE HIGHEST SALARY
SELECT MAX(SALARY) AS MAXIMUM FROM EMPLOYEES
WHERE DEPARTMENT="HR";

-- IN FINANCE DEPARTMENT WHAT IS TOTAL AMOUNT DISBURSED?
SELECT SUM(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT="FINANCE";

-- GROUP BY CLAUSE : IT WILL GROUP SOME ELEMENT
SELECT DEPARTMENT,COUNT(NAME) FROM EMPLOYEES
GROUP BY DEPARTMENT;

-- HAVING CLAUSE : IT IS SAME AS WHERE CLAUSE BUT USED AFTER THE GROUP BY

SELECT DEPARTMENT,COUNT(NAME)
FROM EMPLOYEES
WHERE CITY="DELHI"
GROUP BY DEPARTMENT
HAVING COUNT(NAME)>1;

-- SELECT
-- FROM
-- WHERE
-- GROUP
-- HAVING
-- ORDER BY
-- LIMIT
-- OFFSET

-- ALTER COMMANDS : HERE WE RENAME,MODIFY OUR COLUMNS,DATA-TYPES ETC....